version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
  kafka_1:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      KAFKA_CREATE_TOPICS: "test:1:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT

      KAFKA_PROTOCOL_NAME: CLIENT
      KAFKA_PORT: 9092
  kafka-client:
    image: aardelean/kafka-client:1.3
    ports:
      - target: 7002
        published:  7002
        protocol: tcp
    environment:
        REST_PROVIDER:  "http://random-rest-generator:7001"
        KAFKA_SERVER: 192.168.0.12:9092
  kafka-consumer:
    image: consumer:1.0
    environment:
        KAFKA_SERVER: 192.168.0.12:9092