version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    deploy:
      replicas: 1
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
    networks:
      - kafka-network
  kafka_1:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9092
    environment:
      KAFKA_CREATE_TOPICS: "test:1:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT
      KAFKA_PROTOCOL_NAME: CLIENT
      KAFKA_PORT: 9092
    networks:
      - kafka-network
  kafka_2:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9093
    environment:
      KAFKA_CREATE_TOPICS: "test:1:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT
      KAFKA_PROTOCOL_NAME: CLIENT
      KAFKA_PORT: 9093
    networks:
      - kafka-network
  kafka_3:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9094
    environment:
      KAFKA_CREATE_TOPICS: "test:1:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT
      KAFKA_PROTOCOL_NAME: CLIENT
      KAFKA_PORT: 9094
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: overlay