version: '3.5'
services:
  random-rest-generator:
    image: aardelean/random-rest-generator:H
    ports:
      - target: 7001
        published:  7001
        protocol: tcp
    networks:
      - rest-network
  kafka-producer:
    image: aardelean/kafka-client:1.5
    ports:
      - target: 7002
        published:  7002
        protocol: tcp
    networks:
      - rest-network
      - batch_kafka-network
    environment:
        REST_PROVIDER:  http://random-rest-generator:7001
        KAFKA_SERVER: 192.168.0.12:9092,192.168.0.12:9093,192.168.0.12:9094
  kafka-consumer:
    image: consumer:1.0
    environment:
        KAFKA_SERVER: 192.168.0.12:9092,192.168.0.12:9093,192.168.0.12:9094
    networks:
      - batch_kafka-network

networks:
  rest-network:
    driver: rest-network
  batch_kafka-network:
    external: true