server:
  port: 7017
spring:
  application:
    name: batch-backend
  datasource:
    url:  jdbc:postgresql://swarm:5432/batch
    driver: com.postgresql.Driver
    username: postgres
    password: postgres
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL94Dialect
        jdbc:
          lob:
            non_contextual_creation:  true