version: '3.5'
services:
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - target: 9000
        published:  9001
        protocol: tcp
    environment:
      ZK_HOSTS: "zookeeper:2181"
      KM_ARGS:  "-Djava.net.preferIPv4Stack=true"
    extra_hosts:
      - "swarm:${HOST}"